kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: elasticdb-pvc
  annotations:
    helm.sh/resource-policy: keep
spec:
  storageClassName: {{ .Values.volume.StorageClass }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.volume.StorageSize }}

